/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanArray;

/**
 *
 * @author Evolved
 */
public class ProgramAritmatika extends javax.swing.JFrame {
    String jns = "";
    int jml;
    /**
     * Creates new form ProgramAritmatika
     */
    public ProgramAritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        b2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();
        pilihanbil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PROGRAM ARITMATIKA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 10, 180, 17);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis);
        jenis.setBounds(140, 50, 160, 20);

        panel.setBackground(new java.awt.Color(204, 204, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel.setLayout(null);
        panel.add(ket);
        ket.setBounds(110, 10, 110, 30);

        bil2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bil2.setText("BILANGAN 2");
        panel.add(bil2);
        bil2.setBounds(10, 90, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("JUMLAH BILANGAN");
        panel.add(jLabel5);
        jLabel5.setBounds(10, 40, 110, 30);

        bil1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bil1.setText("BILANGAN 1");
        panel.add(bil1);
        bil1.setBounds(10, 70, 110, 30);

        bil3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bil3.setText("BILANGAN 3");
        panel.add(bil3);
        bil3.setBounds(10, 110, 110, 30);

        bil4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bil4.setText("BILANGAN 4");
        panel.add(bil4);
        bil4.setBounds(10, 130, 110, 30);

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        panel.add(b2);
        b2.setBounds(140, 100, 120, 20);

        jTextField3.setText("jTextField1");
        panel.add(jTextField3);
        jTextField3.setBounds(140, 100, 120, 20);
        panel.add(b1);
        b1.setBounds(140, 80, 120, 20);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        panel.add(b4);
        b4.setBounds(140, 140, 120, 20);
        panel.add(b3);
        b3.setBounds(140, 120, 120, 20);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(180, 170, 63, 23);
        panel.add(thasil);
        thasil.setBounds(140, 200, 120, 70);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(140, 50, 120, 20);

        jPanel1.add(panel);
        panel.setBounds(20, 80, 280, 280);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("JENIS ARITMATIKA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 180, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 440, 370);

        setBounds(0, 0, 453, 402);
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();    
// TODO add your handling code here:
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double hsl = 0.0;
        Double a1,a2,a3,a4;
        a1 = Double.parseDouble(b1.getText());
        a2 = Double.parseDouble(b2.getText());
        a3 = Double.parseDouble(b3.getText());
        a4 = Double.parseDouble(b4.getText());
        
        if(jns.equals("Penjumlahan")){
          if(jml == 2){
              hsl = a1 + a2;
              thasil.setText(""+a1+" + "+a2+" = " +hsl);
          }
          if(jml == 3){
              hsl = a1 + a2 + a3;
              thasil.setText(""+a1+" + "+a2+" + "+a3+" = "+hsl);
          }
          if(jml == 4){
              hsl = a1 + a2 + a3 + a4;
              thasil.setText(""+a1+" + "+a2+" + "+a3+" + "+a4+" = " +hsl);
          }
        }
          else if(jns.equals("Pengurangan")){
          if(jml == 2){
              hsl = a1 - a2;
              thasil.setText(""+a1+" - "+a2+" = " +hsl);
          }
          if(jml == 3){
              hsl = a1 - a2 - a3;
              thasil.setText(""+a1+" - "+a2+" - "+a3+" = "+hsl);
          }
          if(jml == 4){
              hsl = a1 - a2 - a3 - a4;
              thasil.setText(""+a1+" - "+a2+" - "+a3+" - "+a4+" = " +hsl);
          }
          }
          else if(jns.equals("Perkalian")){
          if(jml == 2){
              hsl = a1 * a2;
              thasil.setText(""+a1+" x "+a2+" = " +hsl);
          }
          if(jml == 3){
              hsl = a1 * a2 * a3;
              thasil.setText(""+a1+" x "+a2+" x "+a3+" = "+hsl);
          }
          if(jml == 4){
              hsl = a1 * a2 * a3 * a4;
              thasil.setText(""+a1+" x "+a2+" x "+a3+" x "+a4+" = " +hsl);
          }
          
          else if(jns.equals("Pembagian")){
          if(jml == 2){
              hsl = a1 / a2;
              thasil.setText(""+a1+" / "+a2+" = " +hsl);
          }
          if(jml == 3){
              hsl = a1 / a2 / a3;
              thasil.setText(""+a1+" / "+a2+" / "+a3+" = "+hsl);
          }
          if(jml == 4){
              hsl = a1 / a2 / a3 / a4;
              thasil.setText(""+a1+" / "+a2+" / "+a3+" / "+a4+" = " +hsl);
          }
          
          
          
          
          
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
          }
    /**
     *
     */
    public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        jml = 2;
        }
        else if(pilihanbil.getSelectedItem().equals("3")){
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        bil3.setVisible(true);
        bil4.setVisible(false);
        b3.setVisible(true);
        b4.setVisible(false);
        jml = 3;
        }
        else if(pilihanbil.getSelectedItem().equals("4")){
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
        jml = 4;
        }
    }
    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables
}
